language: C
sudo: required
dist: trusty
compiler:
  - gcc
before_install:
  - uname -a
  - sudo apt-get update 
  - sudo apt-get install -y -qq build-essential cmake  
script:
  - mkdir build
  - cd build
  - cmake -G"Unix Makefiles" ../
  - make 
  - make install
  - make ulist_test 
  - make install -C test/
  - make test
